#define I2C_SDA_PIN 4
#define I2C_SCL_PIN 5

#define BUZZER_SOUND_PIN 29

#define MOTOR_LEFT_UP_PIN 27
#define MOTOR_LEFT_DOWN_PIN 26
#define MOTOR_RIGHT_UP_PIN 9
#define MOTOR_RIGHT_DOWN_PIN 10

#define SDCARD_SPIx_SCK_PIN 14
#define SDCARD_SPIx_TX_MOSI_PIN 15
#define SDCARD_SPIx_RX_MISO_PIN 16
#define SDCARD_SPIx_CSn_PIN 17